### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by 7orG** [alfonmga/mercadona-cli#1]
Hi @alfonmga,

I hope you are doing well.

Thank you so much for making this!

I am trying to play with your piece of art a little bit but I have an error when I run the make command, do you know what the problem is?
![image](https://user-images.githubusercontent.com/18755290/130338934-3607f734-4a64-4e2c-8bf2-f07bf35de5c0.png)

Thank you in advance!

**Comment by exwyezed** [comment]
Hi @7orG, I'm glad you found this little project useful. Looking at that error I think it's failing because you don't have Golang installed. [You can install it from here](https://golang.org/doc/install).

[This question on StackOverflow may help you too.](https://stackoverflow.com/questions/33674973/makefile-error-make-e-2-the-system-cannot-find-the-file-specified)

**Comment by 7orG** [comment]
Hi @alfonmga,

Thank you for your fast and accurate answer! It solved my issue.

Gonna try it out!
